# Site settings
title: OMDB - Open Music Data Base
email: slpixe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Site for messing around with artists/songs
baseurl: "/omdb/" # the subpath of your site, e.g. /blog/
url: "http://slpixe.github.io/omdb/" # the base hostname & protocol for your site
twitter_username: slpixe
github_username:  slpixe

# Build settings
markdown: kramdown

kramdown:
  input: GFM

collections:
  artists:
    output: true